### ISSUE TITLE
[SPEC] Add Metrics to the relayer

### ISSUE THREAD

**Issue by nepoche** [webb-tools/relayer#216]
While logs are one way to gather information about relayer execution, metrics can be another helpful way. These are a couple metrics which may be helpful to query and understand more about the execution of the relayer:

- [x] How many times did the [BridgeWatcher](https://github.com/webb-tools/relayer/blob/main/src/events_watcher/mod.rs#L317) enter backoff?
- [x] How many times did the routine [handle_proposal](https://github.com/webb-tools/relayer/blob/main/src/events_watcher/proposal_signing_backend/mocked.rs#L64) get called?
- [ ] How many times did this [case](https://github.com/webb-tools/relayer/blob/main/src/tx_queue.rs#L228-L232) get hit?
- [x] How many times did `TxQueue` enter [backoff](https://github.com/webb-tools/relayer/blob/main/src/tx_queue.rs#L288)
- [x] How many times did a proposal attempt to be queued, [when there was already an entry](https://github.com/webb-tools/relayer/blob/main/src/events_watcher/signature_bridge_watcher.rs#L194-L203)

**Additional Statistics to capture:**
- [ ] Total Active Relayers
- [x] Total Fees Earned 
- [x] Total Transaction made
- [x] Gas Spent
- [x] Number of proposals proposed
- [x] Amount of data stored

These metrics should be grouped by chain and retrievable via the api: `api/v1/metrics/:chainId`. It may make sense to add metrics data to the store (and reset on startup).

**Comment by shekohex** [comment]
I do not think we will need to define an enum type for each of these values, instead we would just have one simple sharable struct called `RelayerMetrics` which will be stored in an `Arc` inside the `RelayerContext` so that it will be shared for the whole relayer. inside the `ctx.metrices` we will have many fields, each field represent a counter or other types of telemetry. an example of this can be found [here](https://github.com/tikv/rust-prometheus/blob/fc591fdee0ffc75cd26d8a7f82f8e2c4c66bb1ff/examples/example_int_metrics.rs)

**Comment by dharjeezy** [comment]
> I do not think we will need to define an enum type for each of these values, instead we would just have one simple sharable struct called `RelayerMetrics` which will be stored in an `Arc` inside the `RelayerContext` so that it will be shared for the whole relayer. inside the `ctx.metrices` we will have many fields, each field represent a counter or other types of telemetry. an example of this can be found [here](https://github.com/tikv/rust-prometheus/blob/fc591fdee0ffc75cd26d8a7f82f8e2c4c66bb1ff/examples/example_int_metrics.rs)

Alright. This works too
