### ISSUE TITLE
[BUG] Subsequent relayer withdraw transactions hit errors

### ISSUE THREAD

**Issue by nepoche** [webb-tools/relayer#73]
### Overview

While updating integration tests for the relayer to withdraw from subsequent deposits, off of branch `nathan/relayer-subsequent-deposit-issues` the following issue is observed.

### Observed Behavior

` 2022-01-10T13:58:50.546761Z ERROR webb_relayer::tx_queue: Error while sending tx 0x5a5b33473ea4898d5d7ac94414895e19bb5c66b4b316fee615169e8d9c6674ef, (code: -32000, message: VM Exception while processing transaction: revert New leaf index must be greater, data: Some(Object({"name": String("c"), "stack": String("c: VM Exception while processing transaction: revert New leaf index must be greater\n    at Function.c.fromResults (/Users/nathanbarnavon/workspace/relayer/tests/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:192416)\n    at e.exports (/Users/nathanbarnavon/workspace/relayer/tests/node_modules/ganache-cli/build/ganache-core.node.cli.js:55:2089395)")})))`

### Expected Behavior

The relayed withdraw should work successfully

**Comment by nepoche** [comment]
Full logs available here:
[RelayerSubsequentDeposits.txt](https://github.com/webb-tools/relayer/files/7839802/RelayerSubsequentDeposits.txt)

**Comment by shekohex** [comment]
From Reading the Logs you provided, it sounds like there is something wrong with the event watcher, it always get the old events again and again for some reason, which is not good, I'm not sure is the something wrong with ganache itself or we have something in our events watcher regards where we start the blocks.

It is like the following:
```python
while (True):
	step = 50
	start_block = get_last_saved_block()
	last_block = get_last_block_from_chain()
	dest_block = min(start_block + step, last_block)
	events = fetch_events_from_chain(start_block, dest_block)
	process_events(events)
	save_last_block(dest_block)
```

What Happen is, when we start again, it sounds like we got all the events already from the `dest_block` but in the next loop we get the events again from that block, since the `dest_block` now is the `start_block`.

I wonder if we changed the code to be like `save_last_block(dest_block + 1)` would solve this issue, worth trying it @nepoche .
